spring:
  application:
    name: TestTask
  data:
    mongodb:
      username: admin
      password: admin
      host: mongo
      port: 27017
      database: marveldb
      authentication-database: admin
